env: CartPole-v1                 # or 'LunarLander-v2'                                # environnement 
seed: 5
freqTest: 100                                                                         # testing frequency
nbTest: 10                                                                            # number of test episodes
freqVerbose: 50000                                                                    # verbose frequency
freqOptim: 500                                                                        # learning frequency
nbEpisodes: 500                                                                       # maximal number of episodes
maxLengthTest: 500                                                                    # maximal length of a test episode
maxLengthTrain: 500                                                                   # maximal length of a train episode
K_epochs: 10                                                                          # length of for-loop inside the learning function
discount: 0.99                                                                        # Discount factor
gae_lambda: 0.99                                                                      # Lambda of TD(lambda) advantage estimation
lr_a: 0.0001                                                                          # Learning rate of actor
lr_c: 0.001                                                                           # Learning rate of critic
clip: True                                                                            # choice of algorithm
KL: False                                                                             # choice of algorithm
PPO: False                                                                            # choice of algorithm
