env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 5000
nbTest: 1
freqVerbose: 50000
freqOptim: 500                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 30000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 500                                                                   # Longueur maxi des trajectoires en Train
K_epochs: 10
clip: True
